index.html

Hi @adityaraute! 
I've added website URLs in the navbar's 'Activities' and 'Contact Us' elements. I've added the root route itself in the 'Home' element as I thought it should point to that only, and as for the last element, I have made no changes as it is primarily used to switch the website's language.
I hope you like it and please let me know if you want me to change anything or in case of any feedback, thanks!

#1 added external website links to navbar elements

---

assets/css/style.css

I changed your background color from black to Desert Sand.

background color change

---

activities.html
assets/css/style.css
contact.html

Hey, I think this should be good to go. Let me know.

Added contact and activities files, changes in style.css

---

index.html

The issue is fixed you can merge the branch!

typo in img tag fixed

---

assets/css/style.css
index.html

**The image has been made responsive on all devices**
This resolves the issue #28

Image Responsiveness

---

index.html

Fixes #44 
Changes proposed 
Test Methodology and Results
Now all the links of social media pages open in new tabs.

Update index.html to update opening of social links in new tab

---

activities.html
assets/css/activities.css
assets/css/gallery.css
assets/css/style.css
gallery.html
images.json
script/main.js

Fixes #
Changes Proposed
- Add new images.json File
- Added new gallery.html File to render the gallery
- Added new script to pull images from json file
Test Methodology and Results
- Used new gallery.html page to render the gallery.

Implemented a responsive grid gallery that gets images from a json file

---

assets/css/style.css

This change improves accessibility by showing text clearly
Fixes #
https://github.com/rbjks/rbjks.github.io/issues/57
I removed #ccc color on navbar and #intro-text, and replaced it #fff

Change navbar and body text color to white

---

assets/css/contact.css

Maintains consistent font color through out the website.
Fixes #63
Changed navbar text color from black to white.
Using a browser. Screenshots attached. 
User live server extension in vs code. Checked if all navbar elements have same color.

CSS: fix font color on contacts page 

---

assets/css/contact.css
contact.html

I commented on the line that assigned background color and min height of the footer section tag that was making the footer look weird.
To fix the footer
Fixes #67
Changed CSS code
Live server running test

Footer Fixed by changing CSS

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fixes #64 
I have edited the Markdown
I have Made a testing repo for it
- [ x] Bug fix (non-breaking change that fixes an issue)
- [ x] My code follows the code style of this project.

Added checkbox for issue template

---

activities.html
assets/css/contact.css
contact.html
index.html

Fixes issue #78 
changed logo to favicon

fixes issue #78

---

.github/ISSUE_TEMPLATE/feature_report.yml

removed discord link description
this is solution for issue #92 
Fixes #

Unnecessary link in Issue template #92

---

README.md

Fixes #97 
Added the Gitpod Edit image
I have click on the button from Microsoft Edge, and it worked
- [] My change requires a change to the documentation.

Bashamega patch 1

---

contact.html

Contact page title 

---

assets/css/style.css
index.html

This commit adds a hover effect feature to the mobile view to make the website more responsive.Closes #121.
Screenshot before
screenshots after
- [x ] New feature (non-breaking change that a
- [x ] My code follows the code style of this project.

Add a hover effect feature                                                     

---

assets/css/style.css

Fixes #115 
Changes to margins to make responsive view fit better. 
before: 
after:

changes to margins for mobile view fixes #115

---

activities.html
assets/css/style.css
assets/script/main.js
contact.html
index.html

Fixes #113
Description:-
So as I said I changed the overall mobileview structure of the page with a beautiful toggling of a hamburger. This hamburger has a beautiful animation of from right to left and vice-versa The color of that can be changed to black as well if required
How Has This Been Tested?
I have tested this by running multiple times locally in my local system.
Screenshots (if appropriate):-
Before:-
After:-
Types of Changes:
Checklist:

Hamburger functionality added

---

assets/css/contact.css
assets/css/style.css
contact.html

The contents of the contact section spilled over to the footer when the website was viewed on small devices.
Issue: [link](https://github.com/rbjks/rbjks.github.io/issues/123)
- Changed the contact section (.contact) height attribute to min-height. This made sure that it has 100vh height on large devices as well as the height increases if the content needs more space on smaller screens.
- Fixed indentation issues in contact.css, style.css, and contact.html.
- Moved contact section styling from style.css to contact.css and removed repeated CSS rules. 
Tested on different screen sizes using browser dev tools. Tested on Mozilla Firefox and Google Chrome.

Contact section responsiveness and css clean-up

---

activities.html

Commented the necessary div class
Checked on browser

Commented Twitter widget

---

assets/css/style.css

Fixes #124 
Added new styling rules to the main logo in larger screens, and in the text that was breaking letters when in mobile.
Now in mobile, the main logo is aligned in the middle with the text and the text now only breaks words not letters.
I tested with multiple dimensions. And actually doesn't affect any other areas.

chore: Update CSS to improve footer image and text styling
